version: '3.8'

services:
  nginx:
    build: nginx
    container_name: day_2_nginx
    ports:
      - "2820:80"   # truy cập localhost:2820 trên Windows
      - "2821:81"   # truy cập localhost:2821 trên Windows
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # ":ro" chi duoc phep doc ben host (./nginx/default.conf)
      - ./nginx/day2.conf:/etc/nginx/conf.d/day2.conf
      - ./html:/usr/share/nginx/html_day2    # khong co ":ro" nen duoc phep read-write ben host (day_2/html)
