version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: day17_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: day17_backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  cache-invalidation:
    build: ./cache-invalidation
    container_name: day17_cache_invalidation
    volumes:
      - ./cache-invalidation:/app
      - /app/node_modules

  nginx-gateway:
    build: ./nginx-gateway
    container_name: day17_nginx
    volumes:
      - ./nginx-gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx-gateway/lua:/usr/local/openresty/nginx/lua:ro
    ports:
      - "8217:8217"
    depends_on:
      - backend
      - redis
