version: "3.9"

services:
  server1:
    build:
      context: ./backend/server1
      dockerfile: ../../Dockerfile.backend
    container_name: server_15_1
    ports:
      - "3001:3001"

  server2:
    build:
      context: ./backend/server2
      dockerfile: ../../Dockerfile.backend
    container_name: server_15_2
    ports:
      - "3002:3002"

  server3:
    build:
      context: ./backend/server3
      dockerfile: ../../Dockerfile.backend
    container_name: server_15_3
    ports:
      - "3003:3003"
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "8215:82"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - server1
      - server2
      - server3
