version: '3.8'

services:
  server_polling:
    build: ./server_polling
    container_name: day_16_server_polling_1
    volumes:
      - ./server_polling:/app
      - /app/node_modules
    expose:
      - "3000"

  server_push:
    build: ./server_push
    container_name: day_16_server_push_1
    volumes:
      - ./server_push:/app
      - /app/node_modules
    expose:
      - "3001"

  server_chat:
    build: ./server_chat
    container_name: day_16_server_chat_1
    volumes:
      - ./server_chat:/app
      - /app/node_modules
    expose:
      - "3002"

  server_lowlatency:
    build: ./server_lowlatency
    container_name: day_16_server_lowlatency_1
    volumes:
      - ./server_lowlatency:/app
      - /app/node_modules
    expose:
      - "3003"

  redis:
    image: redis:6.2-alpine
    container_name: redis_pubsub
    ports:
      - "6379:6379"

  gateway_ws:
    build: ./gateway_ws
    container_name: gateway_ws
    ports:
      - "8217:3000"  # WS client connect vào đây
    depends_on:
      - redis

  nginx:
    build: ./nginx
    container_name: day16_nginx
    ports:
      - "8216:80"
