version: '3.8'

services:
  server_polling:
    build: ./server_polling
    container_name: day_16_server_polling_1
    volumes:
      - ./server_polling:/app
      - /app/node_modules
    expose:
      - "3000"

  nginx:
    build: ./nginx
    container_name: day16_nginx
    ports:
      - "8216:80"
