version: '3.8'

services:
  server_polling:
    build: ./server_polling
    container_name: day_16_server_polling_1
    volumes:
      - ./server_polling:/app
      - /app/node_modules
    expose:
      - "3000"

  server_push:
    build: ./server_push
    container_name: day_16_server_push_1
    volumes:
      - ./server_push:/app
      - /app/node_modules
    expose:
      - "3001"

  server_chat:
    build: ./server_chat
    container_name: day_16_server_chat_1
    volumes:
      - ./server_chat:/app
      - /app/node_modules
    expose:
      - "3002"

  nginx:
    build: ./nginx
    container_name: day16_nginx
    ports:
      - "8216:80"
