version: "3.9"

services:
  nginx:
    image: nginx:1.28.0
    container_name: day13_nginx
    ports:
      - "82:82"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
