version: '3.8'

services:
  server_1:
    build: server_1
    container_name: server_08_01
    expose:
      - "2881"
    volumes:
      - ./server_1:/app
      - /app/node_modules

  server_2:
    build: server_2
    container_name: server_08_02
    expose:
      - "2882"
    volumes:
      - ./server_2:/app
      - /app/node_modules

  nginx:
    build: nginx
    container_name: nginx_08
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
      - "2880:80"
    depends_on:
      - server_1
      - server_2
